# Generated by Django 5.0.6 on 2024-06-11 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('main_id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('street_no', models.CharField(blank=True, max_length=10)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('UNBEARBEITET', 'unbearbeitet'), ('BEARBEITET', 'bearbeitet'), ('ABGESCHLOSSEN', 'abgeschlossen')], default='UNBEARBEITET', max_length=15)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('archiv', models.BooleanField(default=False)),
            ],
        ),
    ]
