version: '3'

services:
  django:
    container_name: einsatzleiter-django
    restart: unless-stopped
    build:
      context: ./Einsatzleiter
      network: host
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./Einsatzleiter:/usr/src/app/
    ports:
      - 8040:8080
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - einsatzleiter-network
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.check-new-mission.schedule: "@every 30s"
      ofelia.job-exec.check-new-mission.command: "python manage.py runscript mission"

  db:
    image: postgres:alpine
    restart: unless-stopped
    container_name: einsatzleiter-postgres
    ports:
      - 5432:5432
    networks:
      - einsatzleiter-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  ofelia:
    # https://github.com/mcuadros/ofelia?tab=readme-ov-file
    image: mcuadros/ofelia:latest
    restart: unless-stopped
    container_name: einsatzleiter-ofelia
    command: daemon --docker
    networks:
      - einsatzleiter-network
    depends_on:
      - django
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-local.django.schedule: "@every 60s"
      ofelia.job-local.django.command: "date"

volumes:
  postgres_data:

networks:
  einsatzleiter-network:
    name: einsatzleiter-network
    driver: bridge