version: '3'


services:
  django:
    container_name: django-mde
    restart: unless-stopped
    build:
      context: ./django-mde
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./django-mde:/usr/src/app/
    ports:
      - 8040:8080
    environment:
#      - PIPELINE=production
      - PIPELINE=test
      - SECRET_KEY=django-insecure-pnxcsdqt#*edu21fs^c4d840sj*9r_#ym9mu@#0m%$ffiasg32
      - ALLOWED_HOSTS=localhost,0.0.0.0
      - DB_NAME=arbeit
      - DB_USER_NM=mitarbeiter
      - DB_USER_PW=arbeitsplatz1
      - DB_IP=django-postgres
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - django-network
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.django-mde.schedule: "@every 30s"
      ofelia.job-exec.django-mde.command: "python manage.py runscript mission"

  db:
    image: postgres:alpine
    restart: unless-stopped
    container_name: django-postgres
    ports:
      - 5432:5432
    networks:
      - django-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mitarbeiter
      - POSTGRES_PASSWORD=arbeitsplatz1
      - POSTGRES_DB=arbeit


  ofelia:
    # https://github.com/mcuadros/ofelia?tab=readme-ov-file
    image: mcuadros/ofelia:latest
    restart: unless-stopped
    container_name: django-ofelia
    command: daemon --docker
    networks:
      - django-network
    depends_on:
      - django
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-local.django.schedule: "@every 60s"
      ofelia.job-local.django.command: "date"

volumes:
  postgres_data:

networks:
  django-network:
    name: django-network
    driver: bridge